### ISSUE TITLE
Implement failsafes

### ISSUE THREAD

**Issue by MikaelFangel** [MikaelFangel/GolfBot#112]
- [x] Handle if the robot's main crash, and the client should reconnect
- [ ] Make robot stop completely, if everything goes bad.
- [x] Handle if the client crashes.
- [ ] Handle if we lose connection to robot.

**Comment by Greve2001** [comment]
I have updated the robot.service, we need to verify that it does indeed restart after 1 second

**Comment by Greve2001** [comment]
I have made an Emergency Stop method in RobotController. Im not sure were to call it yet, would like to discuss it.
