### ISSUE TITLE
Create visual detection for golf balls and course frame

### ISSUE THREAD

**Issue by MikaelFangel** [MikaelFangel/GolfBot#18]
- [x] Research opencv
- [x] Detect 1 or multiple balls
- [x] Detect course frame
- [x] Calculate coordinate system
- [x] Test precision and camera distortion effects

We might need to look into camera distortion to solve the mapping of coordinaters from pixels to irl measurements

**Comment by MadSoeDK** [comment]
We can from the detection of the balls and frame calculate irl coordinates and lengths between points. We still need to test the effect of camera distortion and the precision of the calculations.

**Comment by MikaelFangel** [comment]
I've added a sub task for this (:

**Comment by MadSoeDK** [comment]
I have written test result in overleaf

**Comment by MadSoeDK** [comment]
I added detection to the cross in the middle of the course frame.
