### ISSUE TITLE
Research how to detect robots rotation and position and implement

### ISSUE THREAD

**Issue by MikaelFangel** [MikaelFangel/GolfBot#20]
- [x] Locate Mark from video feed
- [x] Get rotation from marker
- [ ] ~Convert rotation to usable units~

**Comment by Greve2001** [comment]
The current way we tried to solve the issues cannot work. This will need to be reworked.

The way to solve this is by using to markers of different profiles, to calculate the angle from 2 points, using polar coordinates.

This means that the task will be even more late

**Comment by Greve2001** [comment]
I have implemented a python fuction that gets the center from a center marker and a direction marker.
Using these coordinates we can calculate the angle and so on using polar coordinates.

I have decided that this task of converting to an angle is to be done later when acutally calucation paths and so on.

I just now need to calibrate it using the camera.

**Comment by MikaelFangel** [comment]
@Greve2001 Can I check of the subtask? And where is the pull request closing this issue? (:

**Comment by Greve2001** [comment]
@MikaelFangel I have not yet converted it to Java, so i should maybe have added a subtask for that.
I have also not converted it to angles, so it is techically not considered usable in some sense.

But i have create a new task for conerting it to java. So you can close it if that makes more sense.
Probably should :)

**Comment by MikaelFangel** [comment]
So, this issue should be reopened, correct?

**Comment by Greve2001** [comment]
This has been implemented. Just now needs to be merged with the Java conversion issue
