### ISSUE TITLE
Correct Camera view to Actual Course Layout

### ISSUE THREAD

**Issue by MikaelFangel** [MikaelFangel/GolfBot#63]
We need to make sure that there is next to little loss in precision from what the camera sees to how the course is really layed out.

- [ ] (DROPPED) Correct camera lens distortion, if needed
- [ ]  Map coordinate system to course, instead of camera frame

**Comment by Greve2001** [comment]
We have dropped 2 of the subtasks after trying hard to make them work. We have determined that we can get a relatively precise performance by taking time to setup the camera to be close to

**Comment by Greve2001** [comment]
Time used at this point
Lens undistortion time used: 16 (F)
Warping and stretchig 30 (C) + 3 (F)
